webTutorial/DjangoBasics/mysite/books/urls.py
from django.conf.urls import url
from django.contrib import admin
#this imports from current directory.
from . import views

##this will redirect it to views file index method
## the pattern is what redirect to specific view if multiple views are present
app_name = 'books'

urlpatterns = [
    ####url(r'^$',views.index,name='index'),
    #/books/2
    ####url(r'^(?P<book_id>[0-9]+)/$',views.detail,name='detail'),
    url(r'^$',views.IndexView.as_view(),name='index'),
    # /books/2
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),

    url(r'^add-book/$',views.BookCreate.as_view(),name='book-add'),
]

webTutorial/DjangoBasics/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    ##add this to redirect to books app
    url(r'^books/', include('books.urls')),
]

webTutorial/DjangoBasics/mysite/books/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import  reverse

# Create your models here.

##class name is table name
class Book(models.Model):

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'pk':self.pk})

    ##this will override string calls
    ##when call Book.objects.all() will show this
    def __str__(self):
        return self.name+'-'+self.author

    ##column name and attribures
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    book_image = models.CharField(max_length=1000)



#class table_name(models.Model):
   #columnname = models.column_Type(attributes)

webTutorial/DjangoBasics/mysite/books/views.py
##this is generic view implementation of views
from django.views import generic
from .models import Book
from django.views.generic.edit import CreateView

class IndexView(generic.ListView):
    template_name = 'books/index.html'

    def get_queryset(self):
        return Book.objects.all()

class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'

class BookCreate(CreateView):
    model = Book
    fields = ['name','author','price','type','book_image']

webTutorial/DjangoBasics/mysite/books/templates/books/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Store</title>
     <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}">
     <!-- Latest compiled and minified CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'books:index'  %}">
                    The Book Store
                </a>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav ">
                        <li class="">
                            <a href="{% url 'books:index' %}">
                                <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right ">
                        <li class="">
                            <a href="{% url 'books:book-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Book
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'books:index' %}">
                                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Log Out
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
</body>
</html>

webTutorial/DjangoBasics/mysite/books/templates/books/book_form.html
<!--This needs to be modelname_form always -->
{% extends 'books/base.html' %}

{% block body %}

    <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                   <form class="form-horizotal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                       <div class="form-group">
                           <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn-sucess">Submit</button>
                           </div>
                       </div>
                   </form>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

webTutorial/DjangoBasics/mysite/books/templates/books/detail.html
<!-- This reads the str function in models books class -->
<!-- Add this to redirect to a common file for stuff that is common to all webpages like navigation bar here-->
{% extends 'books/base.html' %}
{% block body %}
    {{ book }}
    <h1>{{ book.name }}</h1>
    <h4>{{ book.author }}</h4>

{% endblock %}

webTutorial/DjangoBasics/mysite/books/templates/books/form_template.html
{% for field in form %}
    <div class="from-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
{% endfor %}

webTutorial/DjangoBasics/mysite/books/templates/books/index.html
{% extends 'books/base.html' %}

{% block body %}
    <html>
        <head>

        </head>
        <body>
            <ul>
                <!--{ % for book in all_books -->
                {% for book in object_list %}
                    <!-- replaced static url with dynamic url also adding name space-->
                    <li><a href="{% url 'books:detail' book.id %}">{{ book.name }},{{ book.author }}</a></li>
                    <img src="{{ book.book_image }}">
                {% endfor %}
            </ul>
        </body>
    </html>
{% endblock %}